# Generated by Django 3.0.3 on 2020-05-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('classes', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('gr', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('father_cnic_no', models.IntegerField()),
                ('father_contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('date_birth', models.DateField()),
                ('date_admission', models.DateField()),
                ('date_leaving_school', models.DateField(blank=True, null=True)),
                ('Reason_of_leaving', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(max_length=300)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Class')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
    ]
