# Generated by Django 3.0.5 on 2020-05-07 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('persionalnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('currentbps', models.IntegerField()),
                ('cnic', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('dateofapplication', models.DateField()),
                ('dateofjoin', models.DateField()),
                ('dateofmedical', models.DateField()),
                ('dateofregularistation', models.DateField()),
                ('bpsatfirstjoin', models.IntegerField()),
                ('matricpassingyear', models.IntegerField()),
                ('interpassingyear', models.IntegerField()),
                ('graduationyear', models.IntegerField()),
                ('otheraccademics', models.IntegerField()),
                ('bedpassingyear', models.IntegerField()),
                ('bedresultdate', models.DateField()),
                ('otherprofessionalqualification', models.CharField(max_length=10)),
                ('biometricverified', models.BooleanField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=10)),
                ('interdistricttransfer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
                ('dateofjoinindivision', models.DateField()),
                ('dateofretirement', models.DateField()),
                ('remarks', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=250)),
                ('headname', models.CharField(blank=True, max_length=50, null=True)),
                ('head', models.CharField(blank=True, max_length=150, null=True)),
                ('training', models.CharField(blank=True, max_length=150, null=True)),
                ('domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Division')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Qualification')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StaffType')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnionCouncil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployDocuments',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(upload_to='static/images/user/%user')),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DocumentType')),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Employ')),
            ],
        ),
    ]
