# Generated by Django 3.0.5 on 2020-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200602_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
