# Generated by Django 3.0.5 on 2020-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200507_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employdocuments',
            name='picture',
            field=models.FileField(upload_to='static/images/user/%user'),
        ),
    ]
