# Generated by Django 3.0.5 on 2020-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200507_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employdocuments',
            name='picture',
            field=models.ImageField(upload_to='static/images/user/'),
        ),
    ]
