# Generated by Django 3.0.5 on 2020-05-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('districtname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('documenttype', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Provence',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('provencename', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('qualificationname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tehsilname', models.CharField(max_length=150)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.District')),
            ],
        ),
        migrations.CreateModel(
            name='UnionCouncil',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ucname', models.CharField(max_length=150)),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tehsil')),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=250)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('divisionname', models.CharField(max_length=150)),
                ('provence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Provence')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Division'),
        ),
    ]
