# Generated by Django 3.0.5 on 2020-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='districtname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='divisionname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='documenttype',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='provence',
            name='provencename',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualificationname',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='type',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tehsil',
            name='tehsilname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='unioncouncil',
            name='ucname',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
