# Generated by Django 3.0.5 on 2020-06-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Activities',
            fields=[
                ('activity_code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('activity_name', models.CharField(max_length=300)),
                ('activity_pics', models.ImageField(upload_to='static/images/user/')),
                ('Date', models.DateField()),
                ('institution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('news', models.TextField()),
                ('date', models.DateField()),
                ('institution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
    ]
