# Generated by Django 3.0.3 on 2020-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default='2020-04-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_activities',
            name='Date',
            field=models.DateField(default='2020-05-13'),
            preserve_default=False,
        ),
    ]
