# Generated by Django 3.0.3 on 2020-05-21 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionrooms',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RoomType'),
        ),
        migrations.AddField(
            model_name='institutionplumbingavailiblity',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionplayground',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionplantation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionfurniture',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionelectricityavailiblity',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionbuildingcondition',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionboundarywall',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institutionarea',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='unioncouncil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnionCouncil'),
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
