# Generated by Django 3.0.5 on 2020-05-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200505_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employdocuments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employ'),
        ),
    ]
