# Generated by Django 3.0.5 on 2020-05-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200505_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employdocuments',
            old_name='user',
            new_name='employ',
        ),
    ]
