# Generated by Django 3.0.3 on 2020-05-06 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stafftype'),
        ('user', '0005_auto_20200505_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.StaffType'),
            preserve_default=False,
        ),
    ]
