# Generated by Django 3.0.3 on 2020-05-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employ_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='persionalnumber',
        ),
    ]
