# Generated by Django 3.0.3 on 2020-05-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_employ_persionalnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ',
            old_name='semis_id',
            new_name='persionalnumber',
        ),
    ]
